extensions:
    pim-product-edit-form-save:
        module: workflow/product/save

    pim-product-edit-form-delete:
        module: workflow/product/delete

    pim-product-edit-form-meta-draft-status:
        module: workflow/product/form/meta/draft-status
        parent: pim-product-edit-form-meta
        targetZone: meta
        position: 130

    pim-product-edit-form-working-copy:
        module: workflow/product/form/working-copy
        parent: pim-product-edit-form
        targetZone: self
        position: 100

    pim-product-edit-form-proposals:
        module: workflow/product/form/proposals
        parent: pim-product-edit-form-column-tabs
        aclResourceId: bolgatty_product_or_product_model_proposals
        targetZone: container
        position: 115
        config:
            datagridName: product-draft-grid
            tabCode: pim-product-or-product-model-edit-form-proposals
        
    pim-product-edit-send-for-approval:
        module: workflow/product/form/send-for-approval
        parent: pim-product-edit-form-secondary-actions
        targetZone: secondary-actions
        aclResourceId: bolgatty_product_or_product_model_send_for_approval
        position: 100
        config:
            idKeyName: productId
            route: bolgatty_workflow_product_draft_ready
