services:    
    bolgatty.controller.product_draft_rest:
        public: true
        class: Bolgatty\WorkFlowBundle\Controller\Rest\ProductDraftController
        arguments:
            - '@security.authorization_checker'
            - '@bolgatty.repository.product_draft'
            - '@bolgatty.manager.product_draft'
            - '@pim_catalog.repository.product'
            - '@pim_internal_api_serializer'
            - '@security.token_storage'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_datagrid.datagrid.configuration.product.filters_configurator'
            - '@pim_datagrid.extension.filter'

    bolgatty.controller.product_model_draft_rest:
        public: true
        class: Bolgatty\WorkFlowBundle\Controller\Rest\ProductModelDraftController
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@security.token_storage'
            - '@bolgatty.repository.product_model_draft'
            - '@security.authorization_checker'
            - '@bolgatty.manager.product_model_draft'
            - '@pim_internal_api_serializer'
            - '@pim_user.context.user'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'


            

    pim_enrich.controller.rest.product:
        public: true
        class: 'Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\ProductController'
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.updater.product'
            - '@bolgatty.saver.product_delegating'
            - '@pim_internal_api_serializer'
            - '@pim_catalog.validator.product'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_enrich.filter.product_edit_data'
            - '@pim_catalog.remover.product'
            - '@pim_catalog.builder.product'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_enrich.normalizer.product_violation'
            - '@pim_catalog.builder.product'
            - '@pim_enrich.filter.product_attribute_filter'
            - '@akeneo_elasticsearch.client.product_and_product_model'

    pim_enrich.controller.rest.product_model:
        public: true
        class: 'Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\ProductModelController'
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@pim_internal_api_serializer'
            - '@pim_user.context.user'
            - '@pim_catalog.filter.chained'
            - '@pim_catalog.localization.localizer.converter'
            - '@pim_catalog.comparator.filter.product_model'
            - '@pim_enrich.converter.enrich_to_standard.product_value'
            - '@pim_catalog.updater.product_model'
            - '@pim_catalog.remover.product_model'
            - '@pim_catalog.validator.product_model'
            - '@bolgatty.saver.product_model_delegating'
            - '@pim_enrich.normalizer.product_violation'
            - '@pim_enrich.normalizer.entity_with_family_variant'
            - '@pim_catalog.factory.product_model'
            - '@pim_enrich.normalizer.violation'
            - '@pim_catalog.repository.family_variant'
            - '@pim_enrich.filter.product_model_attribute_filter'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - '@pim_enrich.filter.product_edit_data'
