services:
    bolgatty.factory.product_draft:
        class: Bolgatty\WorkFlowBundle\Component\Factory\ProductDraftFactory
        arguments:
            - '@pim_catalog.repository.product_model'

    bolgatty.factory.product_model_draft:
        class: Bolgatty\WorkFlowBundle\Component\Factory\ProductModelDraftFactory
        arguments:
            - '@pim_catalog.repository.product_model'

    bolgatty.security.factory.filtered_product:
        class: Bolgatty\WorkFlowBundle\Component\Factory\FilteredEntityFactory          

    bolgatty.security.factory.filtered_product_model:
        class: Bolgatty\WorkFlowBundle\Component\Factory\FilteredEntityFactory

    Bolgatty\WorkFlowBundle\Component\Factory\PimUserDraftSourceFactory: ~