services:
    bolgatty.factory.product_draft:
        class: Bolgatty\WorkFlowBundle\Component\Factory\ProductDraftFactory
        arguments:
            - '@pim_catalog.repository.product_without_permission'

    bolgatty.factory.product_model_draft:
        class: Bolgatty\WorkFlowBundle\Component\Factory\ProductModelDraftFactory
        arguments:
            - '@pim_catalog.repository.product_model_without_permission'

    # pimee_workflow.factory.published_product_unique_data:
    #     class: '%pim_catalog.factory.product_unique_data.class%'
    #     arguments:
    #         - '%pimee_workflow.entity.published_product_unique_data.class%'

    # ##User factory
    # pimee_workflow.factory.user.default_proposals_to_review_notification:
    #     class: Akeneo\UserManagement\Component\Factory\SimpleDefaultProperty
    #     public: false
    #     arguments:
    #         $propertyName: 'proposals_to_review_notification'
    #         $defaultPropertyValue: true

    # pimee_workflow.factory.user.default_proposals_state_notifications:
    #     class: Akeneo\UserManagement\Component\Factory\SimpleDefaultProperty
    #     public: false
    #     arguments:
    #         $propertyName: 'proposals_state_notifications'
    #         $defaultPropertyValue: true
    bolgatty.security.factory.filtered_product:
        class: Bolgatty\WorkFlowBundle\Component\Factory\FilteredEntityFactory          

    bolgatty.security.factory.filtered_product_model:
        class: Bolgatty\WorkFlowBundle\Component\Factory\FilteredEntityFactory

    Bolgatty\WorkFlowBundle\Component\Factory\PimUserDraftSourceFactory: ~