services:
    bolgatty_catalog.security.merger.merge_data_on_product:
        class: 'Bolgatty\WorkFlowBundle\Component\Merger\MergeDataOnProduct'
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.entity_with_family_variant.add_parent_to_product'
            - '@pim_catalog.repository.product_model'

    bolgatty_catalog.security.merger.merge_data_on_product_model:
        class: 'Bolgatty\WorkFlowBundle\Component\Merger\MergeDataOnProductModel'
        arguments:
            - '@pim_catalog.repository.product_model'
