parameters:
    bolgatty.repository.entity_with_values_draft.class: Bolgatty\WorkFlowBundle\Doctrine\ORM\Repository\EntityWithValuesDraftRepository
    bolgatty.repository.delegating_product.class: Bolgatty\WorkFlowBundle\Doctrine\ORM\Repository\DelegatingProductRepository
   
services:
    bolgatty.object_manager.product_draft:
        alias: doctrine.orm.entity_manager

    bolgatty.object_manager.product_model_draft:
        alias: doctrine.orm.entity_manager

    bolgatty.repository.product_draft:
        class: '%bolgatty.repository.entity_with_values_draft.class%'
        factory: 'bolgatty.object_manager.product_draft:getRepository'
        arguments: ['%bolgatty.entity.product_draft.class%']
        tags:
            - { name: 'pim_repository' }

    bolgatty.repository.product_model_draft:
        class: '%bolgatty.repository.entity_with_values_draft.class%'
        factory: 'doctrine.orm.default_entity_manager:getRepository'
        arguments: ['%bolgatty.model.product_model_draft.class%']
        tags:
            - { name: 'pim_repository' }

    bolgatty.repository.delegating_product:
        class: '%bolgatty.repository.delegating_product.class%'
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@pim_catalog.repository.product'
            - '@bolgatty.repository.product_draft'
            - '@bolgatty_workflow.applier.draft'

    bolgatty.repository.delegating_product_model:
        class: '%bolgatty.repository.delegating_product.class%'
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@pim_catalog.repository.product_model'
            - '@bolgatty.repository.product_model_draft'
            - '@bolgatty_workflow.applier.draft'