# Bolgatty_auto_sku_generator_configuration:
#     path: /configurations

# webku_auto_sku_generator_configuration_get:
#     path: /rest
#     defaults: { _controller: auto.sku.generator.configuration.controller:getSettingsAction}
#     methods: GET

# Bolgatty_auto_sku_generator_configuration_action:
#     path: /sku
#     defaults: { _controller: auto.sku.generator.configuration.controller:getSkuAction}
#     methods: GET

# Bolgatty_auto_sku_generator_configuration_save:
#     path: /rest/{tab}
#     defaults: { _controller: auto.sku.generator.configuration.controller:postAction, tab: 'settings'}
#     methods: POST

# Bolgatty_auto_sku_generator_configuration_locales:
#     path: /rest/locales
#     defaults: { _controller: auto.sku.generator.configuration.controller:getAkeneoActiveLocalesAction}
#     methods: [GET,POST]



product_draft_rest:
    resource: '@WorkFlowBundle/Resources/config/routing/product_draft_rest.yml'
    prefix: /product_draft

product_model_draft_rest:
    resource: '@WorkFlowBundle/Resources/config/routing/product_model_draft_rest.yml'
    prefix: /product_model_draft

# product_model_draft_rest:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/product_model_draft_rest.yml'
#     prefix: /product_model_draft

# completeness_rest:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/completeness_rest.yml'
#     prefix: /workflow/rest/completeness

# product_draft:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/product_draft.yml'
#     prefix: /product_draft

# proposal:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/proposal.yml'
#     prefix: /proposal


# pimee_workflow_rest_product:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/rest/product.yml'
#     prefix: /workflow

# pimee_workflow_rest_product_model:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/rest/product_model.yml'
#     prefix: /workflow

# pimee_workflow_rest_author_draft:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/rest/author_draft.yml'
#     prefix: /draft

# pimee_datagrid_export:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/pimee_export.yml'
#     prefix: /datagrid/export

# # External API
# external_api_product_draft:
#     resource: '@AkeneoPimWorkflowBundle/Resources/config/routing/external_api/product_draft.yml'
#     prefix: /api/rest/v1