services:
    akeneo_connectivity.connection.install.install_subscriber:
        class: Akeneo\Connectivity\Connection\Infrastructure\Install\InstallSubscriber
        arguments:
            - '@database_connection'
        tags:
            - { name: kernel.event_subscriber }
