datagrid:
    product-draft-grid:
        options:
            entityHint: product_draft
            requireJSModules:
                - workflow/proposal/partial-proposal-builder
                - oro/datafilter-builder
                - oro/datagrid/pagination-input
        source:
            type: bolgatty_datasource_product_draft
            entity: '%bolgatty.entity.product_draft.class%'
            repository_method: createDatagridQueryBuilder
        columns:
            author_label:
                label: bolgatty_workflow.product_draft.author
                type: field
                frontend_type: string
            changes:
                label: bolgatty_workflow.product_draft.changes
                type: twig
                template: WorkFlowBundle:Datagrid:Property/changes.html.twig
                frontend_type: html
            createdAt:
                label: bolgatty_workflow.product_draft.created
                type: field
            status:
                label: bolgatty_workflow.product_draft.status.label
                type: twig
                template: WorkFlowBundle:Datagrid:Property/product_draft_status.html.twig
                frontend_type: html
        properties:
            id: ~
            proposal_id: ~
            document_type: ~
        actions:
            approve:
                type: approve-proposal
                label: bolgatty_workflow.product_draft.action.approve
                launcherOptions:
                    className: AknButton AknButton--apply
                link: approve_link
            refuse:
                type: refuse-proposal
                label: bolgatty_workflow.product_draft.action.refuse
                launcherOptions:
                    className: AknButton AknButton--important
                link: refuse_link
            remove:
                type: remove-proposal
                label: bolgatty_workflow.product_draft.action.remove
                launcherOptions:
                    className: AknButton AknButton--important
                link: remove_link
        action_configuration: '@bolgatty.datagrid.configuration.product_draft.grid_helper->getActionConfigurationClosure'
        # filters:
        #     columns:
        #         attribute:
        #             type:        product_draft_attribute_choice
        #             data_name:   changes.values
        #             label:       bolgatty_workflow.product_draft.attribute.label
        #             options:
        #                 field_options:
        #                     multiple: true
        sorters:
            columns:
                author_label:
                    data_name: author
                status:
                    data_name: status
                createdAt:
                    data_name: createdAt
            default:
                createdAt: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
