datagrid:
    last-executions-grid:
        source:
            type: pim_datasource_job_execution
        options:
            manageFilters: false
            toolbarOptions:
                hide: true
        columns:
            date:
                label:         job_tracker.filter.started_at
                data_name:     createTime
                type:          datetime_with_user_timezone
                frontend_type: datetime
            username:
                label: pim_datagrid.column.username
                data_name: user
                frontendType: label
            status:
                label:         Status
                frontend_type: react
                type: field
                component: pimimportexport/js/JobExecutionStatus
                props:
                    status: string
                    currentStep: integer
                    totalSteps: integer
                    hasWarning: boolean
                    hasError: boolean
            warning:
                label: Warnings
                frontendType: label
                data_name: warningCount
        properties:
            id: ~
            currentStep: ~
            totalSteps: ~
            hasWarning: ~
            hasError: ~
            show_link:
                type: url
                params:
                    - id
        actions:
            show:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--view
                type:      navigate
                label:     pim_datagrid.action.show.title
                link:      show_link
                rowAction: true
