name: Launch update for visual regression tests
on:
  pull_request:
    paths:
      - 'akeneo-design-system/**'
# Maybe we can launch unit & visual in parallel in separate jobs
jobs:
  test:
    name: Launch update for visual regression tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout:master
        uses: actions/checkout@v2
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.13
      - name: Install Packages
        run: cd akeneo-design-system && yarn install
      - name: Launch visual regression tests
        run: cd akeneo-design-system && find . -name '*__image_snapshots__*'  -exec rm -rf {} \; || true && yarn test:visual:run -u
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to a new branch and create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update visual tests for branch ${{ steps.extract_branch.outputs.branch }}
          branch: ${{ steps.extract_branch.outputs.branch }}-visual-update
          base: ${{ steps.extract_branch.outputs.branch }}
      # - name: Create new branch
      #   run: |

      #       git config --global user.email "contact@akeneo.com" && \
      #       git config --global user.name "Github Actions" && \
      #       git checkout -b ${{ steps.extract_branch.outputs.branch }}-visual-update && \
      #       git add -A && \
      #       git commit -m "Update visual tests for branch ${{ steps.extract_branch.outputs.branch }}" && \
      #       git push -u origin ${{ steps.extract_branch.outputs.branch }}-visual-update
